// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: contract/time2go.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_contract_time2go_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_time2go_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_contract_time2go_proto_rawDescGZIP(), []int{0}
}

type DefaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultResponse) Reset() {
	*x = DefaultResponse{}
	mi := &file_contract_time2go_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultResponse) ProtoMessage() {}

func (x *DefaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_time2go_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultResponse.ProtoReflect.Descriptor instead.
func (*DefaultResponse) Descriptor() ([]byte, []int) {
	return file_contract_time2go_proto_rawDescGZIP(), []int{1}
}

func (x *DefaultResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DefaultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_contract_time2go_proto protoreflect.FileDescriptor

const file_contract_time2go_proto_rawDesc = "" +
	"\n" +
	"\x16contract/time2go.proto\x12\atime2go\"\x0e\n" +
	"\fEmptyRequest\"?\n" +
	"\x0fDefaultResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2P\n" +
	"\x0eEventScheduler\x12>\n" +
	"\vHealthCheck\x12\x15.time2go.EmptyRequest\x1a\x18.time2go.DefaultResponseB-Z+github.com/LukmanulHakim18/time2go/contractb\x06proto3"

var (
	file_contract_time2go_proto_rawDescOnce sync.Once
	file_contract_time2go_proto_rawDescData []byte
)

func file_contract_time2go_proto_rawDescGZIP() []byte {
	file_contract_time2go_proto_rawDescOnce.Do(func() {
		file_contract_time2go_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_time2go_proto_rawDesc), len(file_contract_time2go_proto_rawDesc)))
	})
	return file_contract_time2go_proto_rawDescData
}

var file_contract_time2go_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_contract_time2go_proto_goTypes = []any{
	(*EmptyRequest)(nil),    // 0: time2go.EmptyRequest
	(*DefaultResponse)(nil), // 1: time2go.DefaultResponse
}
var file_contract_time2go_proto_depIdxs = []int32{
	0, // 0: time2go.EventScheduler.HealthCheck:input_type -> time2go.EmptyRequest
	1, // 1: time2go.EventScheduler.HealthCheck:output_type -> time2go.DefaultResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_contract_time2go_proto_init() }
func file_contract_time2go_proto_init() {
	if File_contract_time2go_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_time2go_proto_rawDesc), len(file_contract_time2go_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_time2go_proto_goTypes,
		DependencyIndexes: file_contract_time2go_proto_depIdxs,
		MessageInfos:      file_contract_time2go_proto_msgTypes,
	}.Build()
	File_contract_time2go_proto = out.File
	file_contract_time2go_proto_goTypes = nil
	file_contract_time2go_proto_depIdxs = nil
}
