// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: contract/time2go.proto

package contract

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventScheduler_HealthCheck_FullMethodName = "/time2go.EventScheduler/HealthCheck"
)

// EventSchedulerClient is the client API for EventScheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// lib-type:"grpc-client"
type EventSchedulerClient interface {
	HealthCheck(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*DefaultResponse, error)
}

type eventSchedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewEventSchedulerClient(cc grpc.ClientConnInterface) EventSchedulerClient {
	return &eventSchedulerClient{cc}
}

func (c *eventSchedulerClient) HealthCheck(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*DefaultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefaultResponse)
	err := c.cc.Invoke(ctx, EventScheduler_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventSchedulerServer is the server API for EventScheduler service.
// All implementations must embed UnimplementedEventSchedulerServer
// for forward compatibility.
//
// lib-type:"grpc-client"
type EventSchedulerServer interface {
	HealthCheck(context.Context, *EmptyRequest) (*DefaultResponse, error)
	mustEmbedUnimplementedEventSchedulerServer()
}

// UnimplementedEventSchedulerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventSchedulerServer struct{}

func (UnimplementedEventSchedulerServer) HealthCheck(context.Context, *EmptyRequest) (*DefaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedEventSchedulerServer) mustEmbedUnimplementedEventSchedulerServer() {}
func (UnimplementedEventSchedulerServer) testEmbeddedByValue()                        {}

// UnsafeEventSchedulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventSchedulerServer will
// result in compilation errors.
type UnsafeEventSchedulerServer interface {
	mustEmbedUnimplementedEventSchedulerServer()
}

func RegisterEventSchedulerServer(s grpc.ServiceRegistrar, srv EventSchedulerServer) {
	// If the following call pancis, it indicates UnimplementedEventSchedulerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventScheduler_ServiceDesc, srv)
}

func _EventScheduler_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventSchedulerServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventScheduler_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventSchedulerServer).HealthCheck(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventScheduler_ServiceDesc is the grpc.ServiceDesc for EventScheduler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventScheduler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "time2go.EventScheduler",
	HandlerType: (*EventSchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _EventScheduler_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contract/time2go.proto",
}
