// Code generated by proto-gen-svc-interceptor.
// Folder	: "github.com/LukmanulHakim18/time2go/contract"
// File		: "contract/time2go.proto"

// * This file will not be regenerated, if it still exists.

package interceptor

import (
	"context"

	"google.golang.org/protobuf/reflect/protoreflect"
)

// InputValidator interceptor
type InputValidator struct {
	next Interceptor
}

// Do function for process incoming context and request.
func (i *InputValidator) Do(ctx context.Context, request protoreflect.ProtoMessage) error {
	panic("not implement")

	// TODO: Add logic here.

	if i.next == nil {
		return nil
	}
	return i.next.Do(ctx, request)
}

// Set Next Interceptor
func (i *InputValidator) SetNext(interceptor Interceptor) {
	i.next = interceptor
}

// GetInputValidatorInterceptor for get interceptor and set next. *new-feature
func GetInputValidatorInterceptor(next Interceptor) Interceptor {
	return &InputValidator{next: next}
}
