// Code generated by proto-gen-svc-interceptor.
// Folder	: "github.com/LukmanulHakim18/time2go/contract"
// File		: "contract/time2go.proto"

// * This file will not be regenerated, if it still exists.

package interceptor

import (
	"context"

	"github.com/LukmanulHakim18/time2go/contract"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// validateMetadata interceptor
type validateMetadata struct {
	next Interceptor
}

// Do function for process incoming context and request.
func (i *validateMetadata) Do(ctx context.Context, request protoreflect.ProtoMessage) (err error) {
	switch t := request.(type) {
	case *contract.Event:
		err = t.Validate(ctx)
	}
	if i.next == nil {
		return nil
	}
	return i.next.Do(ctx, request)
}

// Set Next Interceptor
func (i *validateMetadata) SetNext(interceptor Interceptor) {
	i.next = interceptor
}

// GetvalidateMetadataInterceptor for get interceptor and set next. *new-feature
func GetvalidateMetadataInterceptor(next Interceptor) Interceptor {
	return &validateMetadata{next: next}
}
