// Code generated by proto-gen-go-kit-transport. DO NOT EDIT.
// * Source: "github.com/LukmanulHakim18/time2go/contract/contract/time2go.proto"

package transport

import (
	"context"

	"github.com/LukmanulHakim18/time2go/contract"
)

type UseCaseContract interface {
	HealthCheck(ctx context.Context, request *contract.EmptyRequest) (response *contract.DefaultResponse, err error) // (unary)
}

type transport struct {
	contract.UnimplementedEventSchedulerServer
	UseCase UseCaseContract
}

func NewTransport(ctx context.Context, useCase UseCaseContract) *transport {
	return &transport{
		UseCase: useCase,
	}
}
